// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zjywztntagsggtowyhmb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpqeXd6dG50YWdzZ2d0b3d5aG1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwOTQ1MjAsImV4cCI6MjA2ODY3MDUyMH0.ifXDqhn-tnbtleEN6rJs_jolbXLAtBwgZ64VtMfvH1I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});